#!/usr/bin/python
import os
import sys
import pyinotify
import pynotify
 
if (len(sys.argv) != 2):
    print "usage: lastline_notify "
    sys.exit(-1)
filename = sys.argv[1]
 
class PTmp(pyinotify.ProcessEvent):
    def process_IN_MODIFY(self, event):
        print "Create: %s " % os.path.join(event.path, event.name)
 
        #get the last line in file
        with open(filename) as myfile:
            msg_text =  (list(myfile)[-1])
 
        msg = pynotify.Notification("Irssi Notification:", msg_text)
        msg.show()
 
wm = pyinotify.WatchManager()
mask = pyinotify.IN_MODIFY
notifier = pyinotify.Notifier(wm, PTmp())
wdd = wm.add_watch(filename, mask, rec=True)
pynotify.init("Irssi")
 
while True:
    try:
        notifier.process_events()
        if notifier.check_events():
            notifier.read_events()
    except KeyboardInterrupt:
        notifier.stop()
        break
